project:
  type: website

website:
  title: "Reporting Bat Survey Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tidy.qmd
      - meta.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

