---
title: "Maps"
bibliography: references.bib
format: 
  html:
     code-fold: true
     code-summary: "Show the code"
number-sections: true
---


```{r}
#| include: false


library(tidyverse)
library(sf)
library(ggspatial)
library(iBats)

```

## Open Street Map

OpenStreetMap[^1] is a map of the world, created by the online community and free to use under an open license. @fig-osm shows a map[^2] of the Lydford transect.

[^1]: <https://www.openstreetmap.org/>
[^2]: Base map is the copyright OpenStreetMap contributors

```{r}
#| warning: false
#| message: false
#| label: fig-osm
#| fig-cap: "Open Street Map of Bat Activity on the Lydford Transect"
###| fig.height: 7

library(tidyverse)
library(sf)
library(ggspatial)
library(iBats)

bat_colours_sci <- c(
  "Barbastella barbastellus" = "#1f78b4",
  "Myotis alcathoe" = "#a52a2a",
  "Myotis bechsteinii" = "#7fff00",
  "Myotis brandtii" = "#b2df8a",
  "Myotis mystacinus" = "#6a3d9a",
  "Myotis nattereri" = "#ff7f00",
  "Myotis daubentonii" = "#a6cee3",
  "Myotis spp." = "#bcee68",
  "Plecotus auritus" = "#8b0000",
  "Plecotus spp." = "#8b0000",
  "Plecotus austriacus" = "#000000",
  "Pipistrellus pipistrellus" = "#ffff99",
  "Pipistrellus nathusii" = "#8a2be2",
  "Pipistrellus pygmaeus" = "#b15928",
  "Pipistrellus spp." = "#fdbf6f",
  "Rhinolophus ferrumequinum" = "#e31a1c",
  "Rhinolophus hipposideros" = "#33a02c",
  "Nyctalus noctula" = "#cab2d6",
  "Nyctalus leisleri" = "#fb9a99",
  "Nyctalus spp." = "#eee8cd",
  "Eptesicus serotinus" = "#008b8b"
)


spatial_data <- Lydford%>% 
  select(Species, bat_time, longitude = Longitude, latitude = Latitude)

# colour values used by scale_fill_manual()
graph_bat_colours <- iBats::bat_colours(spatial_data$Species, colour_vector = bat_colours_sci)

spatial_data <- st_as_sf(spatial_data, coords = c("longitude", "latitude"), 
                 crs = 4326)

ggplot() +
  annotation_map_tile(type = "osm",  zoomin = -2, alpha = 0.5) +
  geom_sf(data = spatial_data, aes(fill = Species, size = bat_time), shape = 21, alpha = 0.5) +
   annotation_scale(location = "tl") +
  annotation_north_arrow(location = "bl", which_north = "true") +
  scale_fill_manual(values = graph_bat_colours) +
  scale_size_area(max_size = 12) +
  labs(size = "Bat Activity (secs)",
      fill = "Species") +
  theme(strip.background = element_rect(fill="black"),
    strip.text = element_text(size=14, colour="white", face = "italic"),
    legend.position = "right",
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    title = element_text(colour = "grey80", size = 14),
    legend.text = element_text(face = "italic"))


```
